name: Release

on:
  push:
    branches: [ release ]

jobs:
  release:
    if: github.repository == 'spring-projects-experimental/r2dbc-micrometer-spring-boot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: spring
          server-username: ARTIFACTORY_USERNAME
          server-password: ARTIFACTORY_PASSWORD
      - name: Validation
        run: ./mvnw -B enforcer:enforce -Drules=requireReleaseDeps,requireReleaseVersion
      - name: Build with Maven
        run: ./mvnw -B javadoc:jar source:jar deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
